In [34]:
#general imports
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

#scipy for testing
import scipy
import scipy.stats
from scipy import stats
from scipy.stats import ttest_ind
import statsmodels.stats.api as sms

# sklearn for distribution transforming
from sklearn.preprocessing import QuantileTransformer

#for visualization
import matplotlib.pyplot as plt
import seaborn as sns

# for fitting the distribution
from fitter import Fitter, get_common_distributions, get_distributions

# other libraries
from pylab import rcParams

In [35]:
%matplotlib inline
rcParams['figure.figsize'] = 5,4

In [36]:
path_to_data = 'C:/Users/dansi/OneDrive/Документы/Files/Data science/Bachelorseminar Cinedom/Data/Output analysis.csv'
df = pd.read_csv(path_to_data)

In [37]:
df.head()

,Replication No.,OldtimeInSystem,OldTotalWaiting,OldQueueMachine,OldQueueCashier,OldQueueSnackbar,NewtimeInSystem,NewTotalWaiting,NewQueueOrder,NewQueuePreparing
0,1,396.378,360.844,0,11.082,349.762,80.652,0.545,0.391,0.154
1,2,432.116,421.271,0,5.233,416.038,84.048,1.673,1.602,0.071
2,3,424.715,399.940,0,0.772,399.168,86.444,1.355,0.603,0.752
3,4,365.179,321.597,0,1.514,320.083,82.388,1.361,1.353,0.008
4,5,508.187,486.210,0,8.860,477.350,81.582,0.598,0.541,0.057

In [38]:
df.describe()

,Replication No.,OldtimeInSystem,OldTotalWaiting,OldQueueMachine,OldQueueCashier,OldQueueSnackbar,NewtimeInSystem,NewTotalWaiting,NewQueueOrder,NewQueuePreparing
count,10.00000,10.000000,10.00000,10.0,10.00000,10.00000,10.000000,10.000000,10.000000,10.000000
mean,5.50000,442.761200,413.95010,0.0,4.10610,409.84400,84.670900,1.963800,1.725200,0.238600
std,3.02765,65.545606,74.74142,0.0,4.10166,75.60475,3.451386,1.528181,1.414302,0.328598
min,1.00000,365.179000,321.59700,0.0,0.00000,320.08300,79.732000,0.545000,0.391000,0.000000
25%,3.25000,401.690250,361.54200,0.0,0.83350,353.18750,81.783500,0.965750,0.681250,0.021000
50%,5.50000,428.415500,410.60550,0.0,2.72150,407.60300,85.246000,1.358000,1.220500,0.107000
75%,7.75000,470.704750,448.25500,0.0,7.66900,447.27275,87.023750,2.699000,2.478750,0.241000
max,10.00000,577.139000,562.35200,0.0,11.08200,561.33400,89.682000,4.830000,4.687000,0.922000

In [39]:
data1 = df['OldtimeInSystem']
data2 = df['NewtimeInSystem']
stat, p = ttest_ind(data1, data2)
print('stat=%.3f, p=%.3f' % (stat, p))
if p > 0.05:
	print('There is significant evidance that the means are equal')
else:
	print('There is no significant evidance that the means are equal')

a = df['OldtimeInSystem']
print( '\n 95% Confidence Interval Status Quo model')
print(sms.DescrStatsW(a).tconfint_mean())

b = df['NewtimeInSystem']
print( '\n 95% Confidence Interval improved model')
print(sms.DescrStatsW(b).tconfint_mean())

stat=17.252, p=0.000
There is no significant evidance that the means are equal

 95% Confidence Interval Status Quo model
(395.87269773748255, 489.6497022625175)

 95% Confidence Interval improved model
(82.20192736238704, 87.13987263761297)

In [40]:
data3 = df['OldTotalWaiting']
data4 = df['NewTotalWaiting']
stat, p = ttest_ind(data3, data4)
print('stat=%.3f, p=%.3f' % (stat, p))
if p > 0.05:
	print('There is significant evidance that the means are equal')
else:
	print('There is no significant evidance that the means are equal')

a = df['OldTotalWaiting']
print( '\n 95% Confidence Interval Status Quo model')
print(sms.DescrStatsW(a).tconfint_mean())

b = df['NewTotalWaiting']
print( '\n 95% Confidence Interval improved model')
print(sms.DescrStatsW(b).tconfint_mean())

stat=17.427, p=0.000
There is no significant evidance that the means are equal

 95% Confidence Interval Status Quo model
(360.4833088092144, 467.41689119078563)

 95% Confidence Interval improved model
(0.8706051920001847, 3.056994807999815)